nginx:
  build: images/nginx
  command: nginx -g "daemon off;"
  links:
    - php
  ports:
    - "80:80"
  environment:
    - VIRTUAL_HOST=api.laravel.thilangapitigala.dev
php:
  build: images/php:7.2
  volumes:
    - ../app:/var/www/html
  working_dir: /var/www/html/public
  command: php-fpm
  links:
    - db
  ports:
    - "9000:9000"
  links:
    - db
  environment:
    - DB_HOST=mysqldb
    - DB_DATABASE=laravel
    - DB_USERNAME=root
    - DB_PASSWORD=password
    - DB_CONNECTION=mysql
    - PHP_XDEBUG_ENABLED=1 # Set 1 to enable.
db:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    - MYSQL_DATABASE=laravel
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_USER=root
    - MYSQL_PASSWORD=password
